ClassPlustMVC/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassPlustMVC.Data;
using ClassPlustMVC.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System.IO.Compression;
using System.Security.Claims;

namespace ClassPlustMVC.Controllers
{
    public class AssignmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<AssignmentsController> _logger;

        public AssignmentsController(ApplicationDbContext context, ILogger<AssignmentsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Assignments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Assignments.Include(a => a.Course);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> CourseAssignment(int? id)
        {
            var applicationDbContext = _context.Assignments.Include(a => a.Course).Where(a=>a.CourseId==id);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> PendingAssignment(int? id)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var studentResponse = _context.Responses
                .Where(r => r.StudentId == userId)
                .Select(r=>r.AssignmentId);
            var pendingAssignments = _context.Assignments.Include(c => c.Course)
                .Where(c => c.CourseId == id && c.Deadline > DateTime.Now && !c.Responses.Any(l => studentResponse.Contains(l.AssignmentId)));
            return View(await pendingAssignments.ToListAsync());
            //var applicationDbContext = _context.Assignments.Include(a => a.Course).Where(a => a.CourseId == id && a.Deadline>DateTime.Now);
            //return View(await applicationDbContext.ToListAsync());
        }

        // GET: Assignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .Include(a => a.Course)
                .FirstOrDefaultAsync(m => m.AssignmentId == id);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // GET: Assignments/Create
        public IActionResult Create(int? id)
        {
            ViewData["CourseId"] = id;
            //ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId");
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AssignmentId,Deadline,Topic")] Assignment assignment, IFormFile files,int? id)
        {
            if (ModelState.IsValid)
            {
                assignment.CourseId = id.GetValueOrDefault();
                assignment.PostDate = DateTime.Now;

                var filePath = Path.GetTempFileName();

                using (var stream = new MemoryStream())
                {
                    await files.CopyToAsync(stream);
                    assignment.Question = stream.ToArray();
                }
                string filename= files.FileName;
                string[] filenmeList = filename.Split('.');
                assignment.postType = filenmeList[1];
                _logger.LogCritical(filename);



               
                _context.Add(assignment);
                await _context.SaveChangesAsync();
                return LocalRedirect("~/assignments/CourseAssignment/" + id);
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", assignment.CourseId);
            return View(assignment);
        }

        // GET: Assignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.FindAsync(id);
            if (assignment == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", assignment.CourseId);
            return View(assignment);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AssignmentId,CourseId,PostDate,Deadline,Topic,Question")] Assignment assignment)
        {
            if (id != assignment.AssignmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assignment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssignmentExists(assignment.AssignmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseId", assignment.CourseId);
            return View(assignment);
        }

        public FileResult DownloadFile(int? id)
        {
            _logger.LogCritical(id.ToString());

            var assignment = _context.Assignments.Include(a=>a.Course).FirstOrDefault(a=>a.AssignmentId==id);

            
                if (assignment.postType.Equals("zip"))
                {
                    MemoryStream stream = new MemoryStream(assignment.Question);
                string fileName = assignment.Course.CourseName + " Asignment " + assignment.AssignmentId+".zip";
                    var zippedFile = GetZippedFiles(stream, "file");
                    return File(zippedFile, // We could use just Stream, but the compiler gets a warning: "ObjectDisposedException: Cannot access a closed Stream" then.
                                "application/zip",
                                fileName);
                }

                else
                {

                string fileName= assignment.Course.CourseName + " Asignment " + id + "."+assignment.postType;
                string downloadType = "application/" + assignment.postType;
                return File(assignment.Question, downloadType, fileName);
                }
            
           
            
        }

        // GET: Assignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .Include(a => a.Course)
                .FirstOrDefaultAsync(m => m.AssignmentId == id);
            if (assignment == null)
            {
                return NotFound();
            }
           

            return View(assignment);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assignment = await _context.Assignments.FindAsync(id);
            _context.Assignments.Remove(assignment);
            await _context.SaveChangesAsync();
            return LocalRedirect("~/assignments/CourseAssignment/" + assignment.CourseId);
        }

        private bool AssignmentExists(int id)
        {
            return _context.Assignments.Any(e => e.AssignmentId == id);
        }

        private byte[] GetZippedFiles(MemoryStream originalFileStream, string fileName)
        {
            using (MemoryStream zipStream = new MemoryStream())
            {
                using (ZipArchive zip = new ZipArchive(zipStream, ZipArchiveMode.Create, true))
                {
                    var zipEntry = zip.CreateEntry(fileName);
                    using (var writer = new StreamWriter(zipEntry.Open()))
                    {
                        originalFileStream.WriteTo(writer.BaseStream);
                     
                    }
                    
                   
                }
                return zipStream.ToArray();
            }
        }



    }
}

ClassPlustMVC/Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassPlustMVC.Data;
using ClassPlustMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Security.Claims;
using System.IO.Compression;

namespace ClassPlustMVC.Controllers
{
    public class ResponsesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResponsesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Responses
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Responses.Include(r => r.Assignment);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> AssignmentResponse(int? id)
        {
            var applicationDbContext = _context.Responses.Include(r => r.Assignment ).Include(r => r.Student).Where(r=>r.AssignmentId==id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Responses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _context.Responses
                .Include(r => r.Assignment)
                .FirstOrDefaultAsync(m => m.ResponseId == id);
            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        // GET: Responses/Create
        [Authorize(Roles = "student")]
        public IActionResult Create()
        {
            ViewData["AssignmentId"] = new SelectList(_context.Assignments, "AssignmentId", "AssignmentId");
            return View();
        }

        // POST: Responses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "student")]
        public async Task<IActionResult> Create([Bind("ResponseId")] Response response, IFormFile files, int? id)
        {
            if (ModelState.IsValid)
            {
                response.AssignmentId = id.GetValueOrDefault();
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var pendingAssignments = _context.Assignments.FirstOrDefault(a => a.AssignmentId == id);
                

                response.StudentId = userId;
                response.PostDate = DateTime.Now;

                var filePath = Path.GetTempFileName();

                using (var stream = new MemoryStream())
                {
                    await files.CopyToAsync(stream);
                    response.Submission = stream.ToArray();
                }
                string filename = files.FileName;
                string[] filenmeList = filename.Split('.');
                response.postType = filenmeList[1];
                
                _context.Add(response);
                await _context.SaveChangesAsync();
                return LocalRedirect("~/assignments/PendingAssignment/"+pendingAssignments.CourseId);
            }
            ViewData["AssignmentId"] = new SelectList(_context.Assignments, "AssignmentId", "AssignmentId", response.AssignmentId);
            return View(response);
        }

        // GET: Responses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _context.Responses.FindAsync(id);
            if (response == null)
            {
                return NotFound();
            }
            ViewData["AssignmentId"] = new SelectList(_context.Assignments, "AssignmentId", "AssignmentId", response.AssignmentId);
            return View(response);
        }

        // POST: Responses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResponseId,StudentId,AssignmentId,PostDate,Submission,postType")] Response response)
        {
            if (id != response.ResponseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(response);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResponseExists(response.ResponseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AssignmentId"] = new SelectList(_context.Assignments, "AssignmentId", "AssignmentId", response.AssignmentId);
            return View(response);
        }

        // GET: Responses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _context.Responses
                .Include(r => r.Assignment)
                .FirstOrDefaultAsync(m => m.ResponseId == id);
            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        // POST: Responses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _context.Responses.FindAsync(id);
            _context.Responses.Remove(response);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResponseExists(int id)
        {
            return _context.Responses.Any(e => e.ResponseId == id);
        }

        public FileResult DownloadFile(int? id)
        {
            

            var response = _context.Responses.Include(a => a.Assignment).Include(a=>a.Student).FirstOrDefault(a => a.ResponseId == id);


            if (response.postType.Equals("zip"))
            {
                MemoryStream stream = new MemoryStream(response.Submission);
                string fileName = response.Student.FirstName +" "+response.Student.LastName+" Asignment " + response.Assignment.AssignmentId + ".zip";
                var zippedFile = GetZippedFiles(stream, "file");
                return File(zippedFile, // We could use just Stream, but the compiler gets a warning: "ObjectDisposedException: Cannot access a closed Stream" then.
                            "application/zip",
                            fileName);
            }

            else
            {

                string fileName = response.Student.FirstName + " " + response.Student.LastName + " Asignment " + response.Assignment.AssignmentId + "." + response.postType;
                string downloadType = "application/" + response.postType;
                return File(response.Submission, downloadType, fileName);
            }



        }

        private byte[] GetZippedFiles(MemoryStream originalFileStream, string fileName)
        {
            using (MemoryStream zipStream = new MemoryStream())
            {
                using (ZipArchive zip = new ZipArchive(zipStream, ZipArchiveMode.Create, true))
                {
                    var zipEntry = zip.CreateEntry(fileName);
                    using (var writer = new StreamWriter(zipEntry.Open()))
                    {
                        originalFileStream.WriteTo(writer.BaseStream);

                    }


                }
                return zipStream.ToArray();
            }
        }
    }
}

ClassPlustMVC/Views/Assignments/CourseAssignment.cshtml
@model IEnumerable<ClassPlustMVC.Models.Assignment>

@{
    ViewData["Title"] = "CourseAssignment";
}

<h2>Assignments</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PostDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Question)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PostDate, new { @Value = item.PostDate.ToString("dd-MMM-yyyy") })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Topic)
            </td>
            <td>
                <a asp-action="DownloadFile" asp-route-id="@item.AssignmentId">Download</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseName)
            </td>
            <td>
                <a asp-action="AssignmentResponse" asp-route-id="@item.AssignmentId" asp-controller="Responses">Submissions</a>
                <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ClassPlustMVC/Views/Assignments/Create.cshtml
@model ClassPlustMVC.Models.Assignment

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CourseId" class="control-label"></label>
            <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
        </div>*@
            
            <div class="form-group">
                <div class="mdl-textfield mdl-js-textfield ">
                    <label asp-for="Deadline" class="control-label" style="color:#009688"></label>
                    <input type="date" asp-for="Deadline" class="mdl-textfield__input" />
                    <span asp-validation-for="Deadline" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <label asp-for="Topic" class="mdl-textfield__label" style="color:#009688"></label>
                    <input asp-for="Topic" class="mdl-textfield__input" />
                    <span asp-validation-for="Topic" class="text-danger"></span>
                </div>

            </div>
            <div class="mdl-textfield mdl-js-textfield ">
                <label asp-for="Question" class="control-label" style="color:#009688"></label>
                <input type="file" name="files" class="mdl-textfield__input" required />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClassPlustMVC/Views/Assignments/Delete.cshtml
@model ClassPlustMVC.Models.Assignment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Topic)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.CourseId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AssignmentId" />
        <input type="submit" value="Delete" class="btn btn-default mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ClassPlustMVC/Views/Assignments/Details.cshtml
@model ClassPlustMVC.Models.Assignment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Topic)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.CourseId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AssignmentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ClassPlustMVC/Views/Assignments/Edit.cshtml
@model ClassPlustMVC.Models.Assignment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AssignmentId" />
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostDate" class="control-label"></label>
                <input asp-for="PostDate" class="form-control" />
                <span asp-validation-for="PostDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Topic" class="control-label"></label>
                <input asp-for="Topic" class="form-control" />
                <span asp-validation-for="Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClassPlustMVC/Views/Assignments/Index.cshtml
@model IEnumerable<ClassPlustMVC.Models.Assignment>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PostDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Question)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PostDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Topic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AssignmentId">Edit</a> |
                <a asp-action="DownloadFile" asp-route-id="@item.AssignmentId">Download</a> |
                <a asp-action="Delete" asp-route-id="@item.AssignmentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ClassPlustMVC/Views/Assignments/PendingAssignment.cshtml
@model IEnumerable<ClassPlustMVC.Models.Assignment>

@{
    ViewData["Title"] = "PendingAssignments";
}

<h2>Pending Assignments</h2>

<div class="row">
    @foreach (var item in Model)
    {



        <div class="demo-card-square mdl-card mdl-shadow--2dp col-sm-5" style=" margin-bottom:15px; margin-left:10px; padding-left:0px">
            <div class="mdl-card__title mdl-card--expand" style="background: #00467F; background: -webkit-linear-gradient(to right, #A5CC82, #00467F); background: linear-gradient(to right, #A5CC82, #00467F); width:80rem;">
                <h2 class="mdl-card__title-text" style="color:white"> @Html.DisplayFor(modelItem => item.Topic)</h2>
            </div>
            <div class="mdl-card__supporting-text" style="padding-left:15px">
                <div class="row">
                    <div class="col-sm-3">
                        <h6> @Html.DisplayNameFor(model => model.Course)</h6>
                    </div>
                    <div class="col-sm-6">
                        <h6> @Html.DisplayFor(modelItem => item.Course.CourseName)</h6>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <h6>@Html.DisplayNameFor(model => model.PostDate)</h6>
                    </div>
                    <div class="col-sm-3">
                        <h6>@Html.DisplayFor(modelItem => item.PostDate)</h6>

                    </div>
                    

                </div>

                <div class="row">
                    <div class="col-sm-3">
                        <h6>@Html.DisplayNameFor(model => model.Deadline)</h6>
                    </div>
                    <div class="col-sm-3">
                        <h6>@Html.DisplayFor(modelItem => item.Deadline)</h6>

                    </div>

                </div>

                <div class="row">
                    <form asp-controller="Responses" asp-action="Create" asp-route-id="@item.AssignmentId" enctype="multipart/form-data" method="post">
                        <div class="col-sm-8">
                            <div class="mdl-textfield mdl-js-textfield ">
                            <input type="file" name="files" class="mdl-textfield__input" required/>
                        </div>
                        </div>
                        


                        <div class="col-sm-2">
                            <button type="submit"  class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--primary">
                                <i class="material-icons">attach_file</i>
                            </button>
                            


                        </div>
                    </form>
                        <div class="col-sm-2">
                            <button onclick="location.href='@Url.Action("DownloadFile")/@item.CourseId'" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--primary">
                                <i class="material-icons">attachment</i>
                            </button>

                        </div>
                </div>
            </div>




        </div>

    }
</div>